In [8]:
import pandas as pd
import numpy as np

In [5]:
#crear serie con 5
serie = pd.Series(5)
print(serie)

0    5
dtype: int64


In [6]:
serie = pd.Series(["a", "x", "z"])
print(serie)

0    a
1    x
2    z
dtype: object


In [9]:
array = np.array([2, 4, 6, 8, 10])
serie = pd.Series(array)
print(serie)

0     2
1     4
2     6
3     8
4    10
dtype: int32


In [11]:
#convierte el contenido en texto
serie = pd.Series([1, 2, 3, 4, 5, 6], dtype=np.string_)
print(serie)

0    b'1'
1    b'2'
2    b'3'
3    b'4'
4    b'5'
5    b'6'
dtype: bytes8


In [13]:
#añadir indices
serie = pd.Series([1, 2, 3, 4, 5, 6], index=["A)", "B)", "C)", "D)", "E)", "F)"])
print(serie)

A)    1
B)    2
C)    3
D)    4
E)    5
F)    6
dtype: int64


In [16]:
#crear indices con un diccionario
serie = pd.Series({"A)": 1, "B)": 2, "C)": 3, "D)": 4, "E)": 5, "F)": 6})
print(serie)

A)    1
B)    2
C)    3
D)    4
E)    5
F)    6
dtype: int64


In [18]:
serie = pd.Series([1, 2, 3, 4, 5], index=["A)", "B)", "C)", "D)", "F)"], dtype=np.float64)

In [20]:
serie.values

array([1., 2., 3., 4., 5.])

In [21]:
serie.index

Index(['A)', 'B)', 'C)', 'D)', 'F)'], dtype='object')

In [22]:
serie.index[2]

'C)'

In [24]:
#modificar index
serie.index = [0, 1, 2, 3, 4]
print(serie)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64


In [26]:
#(columna[filas], columna[filas], columna[filas])
dataFrame = pd.DataFrame({"NOMBRE": ["Nahuel", "Patricia", "Lucas"], "EDAD": [20, 30, 10], "SEXO": ["Masculino", "Femenino", "Masculino"]})
print(dataFrame)

     NOMBRE  EDAD       SEXO
0    Nahuel    20  Masculino
1  Patricia    30   Femenino
2     Lucas    10  Masculino


In [30]:
dataFrame = pd.DataFrame({"NOMBRE": pd.Series(["Nahuel", "Patricia", "Lucas"]), "EDAD": pd.Series([20, 30, 10]), "SEXO": pd.Series(["Masculino", "Femenino", "Masculino"])})
print(dataFrame)

     NOMBRE  EDAD       SEXO
0    Nahuel    20  Masculino
1  Patricia    30   Femenino
2     Lucas    10  Masculino


In [31]:
dataFrame = pd.DataFrame({"NOMBRE": ["Nahuel", "Patricia", "Lucas"], "EDAD": np.arange(20, 23), "SEXO": ["Masculino", "Femenino", "Masculino"]})
print(dataFrame)

     NOMBRE  EDAD       SEXO
0    Nahuel    20  Masculino
1  Patricia    21   Femenino
2     Lucas    22  Masculino


In [36]:
tabla = pd.DataFrame(np.arange(20).reshape(5, 4), index=["F1", "F2", "F3", "F4", "F5"], columns=["C1", "C2", "C3", "C4"])
print(tabla)

    C1  C2  C3  C4
F1   0   1   2   3
F2   4   5   6   7
F3   8   9  10  11
F4  12  13  14  15
F5  16  17  18  19


In [38]:
print(tabla.index)

Index(['F1', 'F2', 'F3', 'F4', 'F5'], dtype='object')


In [39]:
print(tabla.columns)

Index(['C1', 'C2', 'C3', 'C4'], dtype='object')


In [40]:
print(tabla.values)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [41]:
tabla = pd.DataFrame(np.arange(20).reshape(5, 4), index=["F1", "F2", "F3", "F4", "F5"], columns=["C1", "C2", "C3", "C4"])
print(tabla)

    C1  C2  C3  C4
F1   0   1   2   3
F2   4   5   6   7
F3   8   9  10  11
F4  12  13  14  15
F5  16  17  18  19


In [42]:
tabla.rename(columns = {"C2": "Columna 2"})

C1  Columna 2  C3  C4
F1   0          1   2   3
F2   4          5   6   7
F3   8          9  10  11
F4  12         13  14  15
F5  16         17  18  19